### PR TITLE
Fixed #15 issue with a notification system

### LINKED ISSUE #15: Persistent login/register errors in Redux.
I found a subtle error in the client application:
* Go to `/login`.
* Enter an incorrect username / password.
* An error is displayed.
* Navigate to `/register`: The error persists with different text.

The same happens when you navigate from `/register` to` /login` with an error.

I think it would be good to create a component to handle errors and that errors will be displayed on the homepage with a disposable alert.

### PR DESCRIPTION
**Pull request by surtich**

### CODE REVIEW

**Comment by yamalight** [comment]
That is some solid work! Have just a few small notes on code and we can merge this 👍

**Comment by surtich** [comment]
I have added some comments. I hope it helps!

**Comment by yamalight** [comment]
@surtich don't see anything new here. are you sure you've pushed those changes? 😄

**Comment by surtich** [comment]
Sorry, I had forgotten to make the PR.

Comments are in:
[building-products-with-js/client/src/store/actions/index.js](https://github.com/DAWZayas/building-products-with-js/blob/ecf3fa3a79651ec467f08617ebfdca8372f104ee/client/src/store/actions/index.js)
building-products-with-js/client/src/store/epics/auth.js(https://github.com/DAWZayas/building-products-with-js/blob/ecf3fa3a79651ec467f08617ebfdca8372f104ee/client/src/store/epics/auth.js)

**Comment by yamalight** [comment]
@surtich ah, okay. now I see them. those definitely look good 👍

**Comment by yamalight** [comment]
@surtich any updates on my requested changes? I'd like to merge this as quick as possible so that I can publish new code from last livestream

**Comment by surtich** [comment]
@yamalight I must have lost something because I thought I had done everything you wanted. Could you clarify me what you want? Thank you.

**Comment by yamalight** [comment]
@surtich ok, that was my stupid mistake - I forgot to submit my review 😞 sorry about that, you should see it now!

**Comment by surtich** [comment]
@yamalight ok. This night I will send you the changes.

**Comment by surtich** [comment]
Here they are the changes you have requested.

**Comment by yamalight** [comment]
@surtich looks great, thank you very much! merging 👍

**Pull request merged**
