### PR TITLE
Fix: user.data value is stored as string in localStorage

### PR DESCRIPTION
**Pull request by surtich**
localStorage seems to be limited to handle only string key/value pairs. See: http://stackoverflow.com/questions/2010892/storing-objects-in-html5-localstoragewq

### CODE REVIEW

**Comment by EliasJorgensen** [comment]
Lol i actually thought about submitting a fix for this, as i have already solved that problem in a personal project of mine. I guess you beat me to it!

**Comment by surtich** [comment]
As @EliasJorgensen said, I had forgotten to use `JSON.parse` to retrieve the user. Thanks.

**Comment by EliasJorgensen** [comment]
Awesome, looks good to me now!

👍 from me, now it's just up to @yamalight 😄

**Comment by yamalight** [comment]
@surtich good point! sometimes forget that stuff 😭 
thanks for PR, merged! 👍

**Pull request merged**
